version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app.py:/app/app.py  # Mount the app code for hot-reloading
      - ./templates:/app/templates       # Mount the html folder
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
